export const FETCH_MEDICINE_OPTIONS_REQUEST = 'FETCH_MEDICINE_OPTIONS_REQUEST';
export const FETCH_MEDICINE_OPTIONS_SUCCESS = 'FETCH_MEDICINE_OPTIONS_SUCCESS';
export const FETCH_MEDICINE_OPTIONS_FAILURE = 'FETCH_MEDICINE_OPTIONS_FAILURE';
